# Generated by Django 3.1.5 on 2021-02-15 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0004_comment_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
